### ISSUE TITLE
How did we end up with duplicate sequences in preview deployment?

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2673]
Fabian made an interesting discovery while reviewing #2667.

Alex investigated and fixed something in silo. But I'm not sure yet we understand fully why the bug only happened in preview now, and not in production.

> What I want to know though: how is it possible that the same issue happened in 3 independent organisms - that all run silo preprocessing independently. If it's stochastic, it should only happen in one instance. Why only in this PR and only now?

_Originally posted by @corneliusroemer in https://github.com/loculus-project/loculus/issues/2667#issuecomment-2321268661_

I wonder whether we have some interaction going on here - maybe this bug only happened due to SILO 0.2.16 - recently released and not heavily tested.

Alternatively, we triggered some rare condition in exactly this preview - but how unlikely is this?

**Comment by Taepper** [comment]
This is indeed very interesting. A `temp` folder that already contains unaligned sequences with primary keys which match the new data.
Then it is up to chance, how duckdb parallelizes its work.
The duckdb SQL that was run by SILO is:
```SQL
COPY 
( SELECT partitioned_metadata."primaryKey" AS key, unaligned_tmp.read AS sequence, partitioned_metadata.partition_id AS partition_id 
  FROM unaligned_tmp 
  RIGHT JOIN partitioned_metadata ON unaligned_tmp.key = partitioned_metadata."primaryKey" )
TO './temp/unaligned_nuc_0' (FORMAT PARQUET, PARTITION_BY (partition_id), OVERWRITE_OR_IGNORE);
```

This partitions the table by `partition_id`, and for every such partition generate a directory containing the data. However, duckdb uses parallelism, which might induce multiple data files per partition directory, which will be called `data_0.parquet`, `data_1.parquet`, `data_2.parquet`...

This should overwrite all files, if there are any, that are already contained in the subdirectories of `./temp/unaligned_nuc_0`.

However, if the next write to this directory uses less parallelism, this might lead to all the data being written to the file `data_0.parquet` and not touching the other files – leaving duplicates in the data.

The following duckdb issues also offer explanations and show more reproducible examples of the bug occuring:
https://github.com/duckdb/duckdb/issues/10282 , https://github.com/duckdb/duckdb/issues/11307


Some guesses why this bug appeared only on the preview:
- The preprocessing in prod. is only run once, whereas in the preview, e.g. ingest is slower and therefore the sequences appear more gradually, leading to multiple preprocessing runs
- The server resources for prod and preview differ in a way, that influenced duckdb's internal parallelization

I suspect, that the bug would have happened if users had started submitting data..

**Comment by chaoran-chen** [comment]
@corneliusroemer, @Taepper – I cannot remember but did you ever find out the reason? Is there still something that we want to do here?

**Comment by Taepper** [comment]
Yes, this was fixed and can be closed IMO

**Comment by elephantmetropolis** [comment]
Hi @Taepper, we still have that exact same problem. With the same machine, on 2 different runs, it will use more or less parallelism and using `COPY` with `PER_THREAD_OUTPUT`, will generate a different number of files, creating duplicates at the end. You said the issue was fixed, how and when ? Thanks !

**Comment by Taepper** [comment]
We fixed it with a solution in our code:
https://github.com/GenSpectrum/LAPIS-SILO/pull/552/files

**Comment by Taepper** [comment]
According to the referenced duckdb issue https://github.com/duckdb/duckdb/issues/10282, it was fixed in `0.10.3`

**Comment by elephantmetropolis** [comment]
Thank you for your quick response. However, it seems the fix is only compatible with local filesystems, not with S3.
Anyway, we found a solution in our code too.
